# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rollNo', models.IntegerField(primary_key=True, serialize=False)),
                ('week', models.ManyToManyField(through='quiz.Points', to='quiz.Week')),
            ],
        ),
        migrations.AddField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.User'),
        ),
        migrations.AddField(
            model_name='points',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Week'),
        ),
    ]
