# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20170622_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='fuck@gmail.com', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown_fucker', max_length=50),
            preserve_default=False,
        ),
    ]
