# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20170622_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ['-point']},
        ),
    ]
