# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('number', models.CharField(max_length=15)),
                ('college', models.CharField(max_length=250)),
                ('paid', models.BooleanField(default=False)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
    ]
