# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('shortId', models.SlugField(max_length=15, primary_key=True, serialize=False)),
                ('httpUrl', models.URLField()),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
