# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='time_stamp',
            new_name='timeStamp',
        ),
    ]
