# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170621_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='shortId',
            field=models.SlugField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
