# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170624_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='urls',
            name='shortUrl',
            field=models.URLField(default='example.com', max_length=100),
        ),
    ]
