# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170707_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='shortId',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
