# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20170707_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='name',
            field=models.CharField(default='xyz', max_length=200),
        ),
    ]
