# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_urls_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
