# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together=set([('c_text', 'question')]),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('q_text', 'form')]),
        ),
    ]
