# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackform', '0002_auto_20170706_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_text', models.CharField(max_length=300)),
                ('c_count', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackform.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='choices',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='choices',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choices',
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('c_text', 'question')]),
        ),
    ]
